### ISSUE TITLE
Infinite 'My year progression' loading

### ISSUE THREAD

**Issue by thomaschampagne** [tazmanska/stravistix#6]
While loading 'My year progression' the athlete (https://www.strava.com/athletes/3193983) is getting infinite loading.

Here are screenshot errors:

![strava3](https://cloud.githubusercontent.com/assets/151973/10423724/aae7533a-70c9-11e5-8628-05153b910d69.jpg)
![strava2](https://cloud.githubusercontent.com/assets/151973/10423725/ab00b4e2-70c9-11e5-88f6-bd9af014c896.jpg)

Reproductibilty: Always for this user.

He is mainly a runner

Some other users reported this problem too.

**It's seems that the requested XHR request (per_page=20&page=9) is not handled. Don't exist? Maybe handle XHR errors and skip result from inside final result?**

I don't know how to debug at the moment since i need to be logged to user account to reproduce the problem.

**Comment by tazmanska** [comment]
@thomaschampagne Is it possible to get a contact to any of those users to get some more information or to debug remotely? Strava responds with 500 so it's hard to say what has went wrong.  The first thought - too many simultaneously requests but they are limited and queued by the browser itself. Ignoring this error is not a solution because the final result would be incorrect. Trying to get a page "out of range" ends with an empty activities list but this example is not about getting an out of range page.

It's impossible to debug this feature in context of the other user than yourself.

**Comment by thomaschampagne** [comment]
@tazmanska i sent you an email about this issue. Because of private data.

Thanks !

Tom

**Comment by tazmanska** [comment]
Fix confirmed by user (corrupted activity).
